---
server:
 port: 8084
spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/adnatahic/NutricionizamFitnes.git
     #username: uname
     #password: pass
     search-paths: 
      - 'Konfiguracija*'
      
